// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: protobuf/ligolo.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_protobuf_ligolo_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_ligolo_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_protobuf_ligolo_proto_rawDescGZIP(), []int{0}
}

type Error struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Object        []byte                 `protobuf:"bytes,1,opt,name=Object,proto3" json:"Object,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=Reason,proto3" json:"Reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Error) Reset() {
	*x = Error{}
	mi := &file_protobuf_ligolo_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_ligolo_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error.ProtoReflect.Descriptor instead.
func (*Error) Descriptor() ([]byte, []int) {
	return file_protobuf_ligolo_proto_rawDescGZIP(), []int{1}
}

func (x *Error) GetObject() []byte {
	if x != nil {
		return x.Object
	}
	return nil
}

func (x *Error) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type Event struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          int32                  `protobuf:"varint,1,opt,name=Type,proto3" json:"Type,omitempty"`
	Data          string                 `protobuf:"bytes,2,opt,name=Data,proto3" json:"Data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_protobuf_ligolo_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_ligolo_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_protobuf_ligolo_proto_rawDescGZIP(), []int{2}
}

func (x *Event) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *Event) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

type Session struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ID               string                 `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Alias            string                 `protobuf:"bytes,2,opt,name=Alias,proto3" json:"Alias,omitempty"`
	Hostname         string                 `protobuf:"bytes,3,opt,name=Hostname,proto3" json:"Hostname,omitempty"`
	Tun              *Tun                   `protobuf:"bytes,4,opt,name=Tun,proto3" json:"Tun,omitempty"`
	IsConnected      bool                   `protobuf:"varint,5,opt,name=IsConnected,proto3" json:"IsConnected,omitempty"`
	IsRelaying       bool                   `protobuf:"varint,6,opt,name=IsRelaying,proto3" json:"IsRelaying,omitempty"`
	Interfaces       []*Interface           `protobuf:"bytes,7,rep,name=Interfaces,proto3" json:"Interfaces,omitempty"`
	Redirectors      []*Redirector          `protobuf:"bytes,8,rep,name=Redirectors,proto3" json:"Redirectors,omitempty"`
	FirstSeen        *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=FirstSeen,proto3" json:"FirstSeen,omitempty"`
	LastSeen         *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=LastSeen,proto3" json:"LastSeen,omitempty"`
	CertOrganization string                 `protobuf:"bytes,11,opt,name=CertOrganization,proto3" json:"CertOrganization,omitempty"` // Certificate Organization field (e.g., "team04")
	CertCommonName   string                 `protobuf:"bytes,12,opt,name=CertCommonName,proto3" json:"CertCommonName,omitempty"`     // Certificate Common Name field (e.g., "team04-agent-167fb1a5")
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Session) Reset() {
	*x = Session{}
	mi := &file_protobuf_ligolo_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Session) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Session) ProtoMessage() {}

func (x *Session) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_ligolo_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Session.ProtoReflect.Descriptor instead.
func (*Session) Descriptor() ([]byte, []int) {
	return file_protobuf_ligolo_proto_rawDescGZIP(), []int{3}
}

func (x *Session) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *Session) GetAlias() string {
	if x != nil {
		return x.Alias
	}
	return ""
}

func (x *Session) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *Session) GetTun() *Tun {
	if x != nil {
		return x.Tun
	}
	return nil
}

func (x *Session) GetIsConnected() bool {
	if x != nil {
		return x.IsConnected
	}
	return false
}

func (x *Session) GetIsRelaying() bool {
	if x != nil {
		return x.IsRelaying
	}
	return false
}

func (x *Session) GetInterfaces() []*Interface {
	if x != nil {
		return x.Interfaces
	}
	return nil
}

func (x *Session) GetRedirectors() []*Redirector {
	if x != nil {
		return x.Redirectors
	}
	return nil
}

func (x *Session) GetFirstSeen() *timestamppb.Timestamp {
	if x != nil {
		return x.FirstSeen
	}
	return nil
}

func (x *Session) GetLastSeen() *timestamppb.Timestamp {
	if x != nil {
		return x.LastSeen
	}
	return nil
}

func (x *Session) GetCertOrganization() string {
	if x != nil {
		return x.CertOrganization
	}
	return ""
}

func (x *Session) GetCertCommonName() string {
	if x != nil {
		return x.CertCommonName
	}
	return ""
}

type Tun struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Routes        []*Route               `protobuf:"bytes,2,rep,name=Routes,proto3" json:"Routes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Tun) Reset() {
	*x = Tun{}
	mi := &file_protobuf_ligolo_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tun) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tun) ProtoMessage() {}

func (x *Tun) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_ligolo_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tun.ProtoReflect.Descriptor instead.
func (*Tun) Descriptor() ([]byte, []int) {
	return file_protobuf_ligolo_proto_rawDescGZIP(), []int{4}
}

func (x *Tun) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Tun) GetRoutes() []*Route {
	if x != nil {
		return x.Routes
	}
	return nil
}

type Interface struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	IPs           []string               `protobuf:"bytes,2,rep,name=IPs,proto3" json:"IPs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Interface) Reset() {
	*x = Interface{}
	mi := &file_protobuf_ligolo_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Interface) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Interface) ProtoMessage() {}

func (x *Interface) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_ligolo_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Interface.ProtoReflect.Descriptor instead.
func (*Interface) Descriptor() ([]byte, []int) {
	return file_protobuf_ligolo_proto_rawDescGZIP(), []int{5}
}

func (x *Interface) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Interface) GetIPs() []string {
	if x != nil {
		return x.IPs
	}
	return nil
}

type Route struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            string                 `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Cidr          string                 `protobuf:"bytes,2,opt,name=Cidr,proto3" json:"Cidr,omitempty"`
	IsLoopback    bool                   `protobuf:"varint,3,opt,name=IsLoopback,proto3" json:"IsLoopback,omitempty"`
	Metric        int32                  `protobuf:"varint,4,opt,name=Metric,proto3" json:"Metric,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Route) Reset() {
	*x = Route{}
	mi := &file_protobuf_ligolo_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Route) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Route) ProtoMessage() {}

func (x *Route) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_ligolo_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Route.ProtoReflect.Descriptor instead.
func (*Route) Descriptor() ([]byte, []int) {
	return file_protobuf_ligolo_proto_rawDescGZIP(), []int{6}
}

func (x *Route) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *Route) GetCidr() string {
	if x != nil {
		return x.Cidr
	}
	return ""
}

func (x *Route) GetIsLoopback() bool {
	if x != nil {
		return x.IsLoopback
	}
	return false
}

func (x *Route) GetMetric() int32 {
	if x != nil {
		return x.Metric
	}
	return 0
}

type Redirector struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            string                 `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Protocol      string                 `protobuf:"bytes,2,opt,name=Protocol,proto3" json:"Protocol,omitempty"`
	From          string                 `protobuf:"bytes,3,opt,name=From,proto3" json:"From,omitempty"`
	To            string                 `protobuf:"bytes,4,opt,name=To,proto3" json:"To,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Redirector) Reset() {
	*x = Redirector{}
	mi := &file_protobuf_ligolo_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Redirector) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Redirector) ProtoMessage() {}

func (x *Redirector) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_ligolo_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Redirector.ProtoReflect.Descriptor instead.
func (*Redirector) Descriptor() ([]byte, []int) {
	return file_protobuf_ligolo_proto_rawDescGZIP(), []int{7}
}

func (x *Redirector) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *Redirector) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *Redirector) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *Redirector) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

type Cert struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	ExpiryDate    string                 `protobuf:"bytes,2,opt,name=ExpiryDate,proto3" json:"ExpiryDate,omitempty"`
	Certificate   []byte                 `protobuf:"bytes,3,opt,name=Certificate,proto3" json:"Certificate,omitempty"`
	Key           []byte                 `protobuf:"bytes,4,opt,name=Key,proto3" json:"Key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Cert) Reset() {
	*x = Cert{}
	mi := &file_protobuf_ligolo_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Cert) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cert) ProtoMessage() {}

func (x *Cert) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_ligolo_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cert.ProtoReflect.Descriptor instead.
func (*Cert) Descriptor() ([]byte, []int) {
	return file_protobuf_ligolo_proto_rawDescGZIP(), []int{8}
}

func (x *Cert) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Cert) GetExpiryDate() string {
	if x != nil {
		return x.ExpiryDate
	}
	return ""
}

func (x *Cert) GetCertificate() []byte {
	if x != nil {
		return x.Certificate
	}
	return nil
}

func (x *Cert) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

type Operator struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	IsAdmin       bool                   `protobuf:"varint,2,opt,name=IsAdmin,proto3" json:"IsAdmin,omitempty"`
	Server        string                 `protobuf:"bytes,3,opt,name=Server,proto3" json:"Server,omitempty"`
	IsOnline      bool                   `protobuf:"varint,4,opt,name=IsOnline,proto3" json:"IsOnline,omitempty"`
	Cert          *Cert                  `protobuf:"bytes,5,opt,name=Cert,proto3" json:"Cert,omitempty"`
	CA            []byte                 `protobuf:"bytes,6,opt,name=CA,proto3" json:"CA,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Operator) Reset() {
	*x = Operator{}
	mi := &file_protobuf_ligolo_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Operator) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Operator) ProtoMessage() {}

func (x *Operator) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_ligolo_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Operator.ProtoReflect.Descriptor instead.
func (*Operator) Descriptor() ([]byte, []int) {
	return file_protobuf_ligolo_proto_rawDescGZIP(), []int{9}
}

func (x *Operator) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Operator) GetIsAdmin() bool {
	if x != nil {
		return x.IsAdmin
	}
	return false
}

func (x *Operator) GetServer() string {
	if x != nil {
		return x.Server
	}
	return ""
}

func (x *Operator) GetIsOnline() bool {
	if x != nil {
		return x.IsOnline
	}
	return false
}

func (x *Operator) GetCert() *Cert {
	if x != nil {
		return x.Cert
	}
	return nil
}

func (x *Operator) GetCA() []byte {
	if x != nil {
		return x.CA
	}
	return nil
}

type Config struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OperatorServer string                 `protobuf:"bytes,1,opt,name=OperatorServer,proto3" json:"OperatorServer,omitempty"`
	AgentServer    string                 `protobuf:"bytes,2,opt,name=AgentServer,proto3" json:"AgentServer,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Config) Reset() {
	*x = Config{}
	mi := &file_protobuf_ligolo_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Config) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Config) ProtoMessage() {}

func (x *Config) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_ligolo_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Config.ProtoReflect.Descriptor instead.
func (*Config) Descriptor() ([]byte, []int) {
	return file_protobuf_ligolo_proto_rawDescGZIP(), []int{10}
}

func (x *Config) GetOperatorServer() string {
	if x != nil {
		return x.OperatorServer
	}
	return ""
}

func (x *Config) GetAgentServer() string {
	if x != nil {
		return x.AgentServer
	}
	return ""
}

type Traceroute struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsInternal    bool                   `protobuf:"varint,1,opt,name=IsInternal,proto3" json:"IsInternal,omitempty"`
	Session       string                 `protobuf:"bytes,2,opt,name=Session,proto3" json:"Session,omitempty"`
	Iface         string                 `protobuf:"bytes,3,opt,name=Iface,proto3" json:"Iface,omitempty"`
	Via           string                 `protobuf:"bytes,4,opt,name=Via,proto3" json:"Via,omitempty"`
	Metric        int32                  `protobuf:"varint,5,opt,name=Metric,proto3" json:"Metric,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Traceroute) Reset() {
	*x = Traceroute{}
	mi := &file_protobuf_ligolo_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Traceroute) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Traceroute) ProtoMessage() {}

func (x *Traceroute) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_ligolo_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Traceroute.ProtoReflect.Descriptor instead.
func (*Traceroute) Descriptor() ([]byte, []int) {
	return file_protobuf_ligolo_proto_rawDescGZIP(), []int{11}
}

func (x *Traceroute) GetIsInternal() bool {
	if x != nil {
		return x.IsInternal
	}
	return false
}

func (x *Traceroute) GetSession() string {
	if x != nil {
		return x.Session
	}
	return ""
}

func (x *Traceroute) GetIface() string {
	if x != nil {
		return x.Iface
	}
	return ""
}

func (x *Traceroute) GetVia() string {
	if x != nil {
		return x.Via
	}
	return ""
}

func (x *Traceroute) GetMetric() int32 {
	if x != nil {
		return x.Metric
	}
	return 0
}

type AddRedirectorReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionID     string                 `protobuf:"bytes,1,opt,name=SessionID,proto3" json:"SessionID,omitempty"`
	Protocol      string                 `protobuf:"bytes,2,opt,name=Protocol,proto3" json:"Protocol,omitempty"`
	From          string                 `protobuf:"bytes,3,opt,name=From,proto3" json:"From,omitempty"`
	To            string                 `protobuf:"bytes,4,opt,name=To,proto3" json:"To,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddRedirectorReq) Reset() {
	*x = AddRedirectorReq{}
	mi := &file_protobuf_ligolo_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddRedirectorReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddRedirectorReq) ProtoMessage() {}

func (x *AddRedirectorReq) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_ligolo_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddRedirectorReq.ProtoReflect.Descriptor instead.
func (*AddRedirectorReq) Descriptor() ([]byte, []int) {
	return file_protobuf_ligolo_proto_rawDescGZIP(), []int{12}
}

func (x *AddRedirectorReq) GetSessionID() string {
	if x != nil {
		return x.SessionID
	}
	return ""
}

func (x *AddRedirectorReq) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *AddRedirectorReq) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *AddRedirectorReq) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

type DelRedirectorReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionID     string                 `protobuf:"bytes,1,opt,name=SessionID,proto3" json:"SessionID,omitempty"`
	RedirectorID  string                 `protobuf:"bytes,2,opt,name=RedirectorID,proto3" json:"RedirectorID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DelRedirectorReq) Reset() {
	*x = DelRedirectorReq{}
	mi := &file_protobuf_ligolo_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DelRedirectorReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelRedirectorReq) ProtoMessage() {}

func (x *DelRedirectorReq) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_ligolo_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelRedirectorReq.ProtoReflect.Descriptor instead.
func (*DelRedirectorReq) Descriptor() ([]byte, []int) {
	return file_protobuf_ligolo_proto_rawDescGZIP(), []int{13}
}

func (x *DelRedirectorReq) GetSessionID() string {
	if x != nil {
		return x.SessionID
	}
	return ""
}

func (x *DelRedirectorReq) GetRedirectorID() string {
	if x != nil {
		return x.RedirectorID
	}
	return ""
}

type GetSessionsResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sessions      []*Session             `protobuf:"bytes,1,rep,name=Sessions,proto3" json:"Sessions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSessionsResp) Reset() {
	*x = GetSessionsResp{}
	mi := &file_protobuf_ligolo_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSessionsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSessionsResp) ProtoMessage() {}

func (x *GetSessionsResp) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_ligolo_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSessionsResp.ProtoReflect.Descriptor instead.
func (*GetSessionsResp) Descriptor() ([]byte, []int) {
	return file_protobuf_ligolo_proto_rawDescGZIP(), []int{14}
}

func (x *GetSessionsResp) GetSessions() []*Session {
	if x != nil {
		return x.Sessions
	}
	return nil
}

type RenameSessionReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionID     string                 `protobuf:"bytes,1,opt,name=SessionID,proto3" json:"SessionID,omitempty"`
	Alias         string                 `protobuf:"bytes,2,opt,name=Alias,proto3" json:"Alias,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RenameSessionReq) Reset() {
	*x = RenameSessionReq{}
	mi := &file_protobuf_ligolo_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenameSessionReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenameSessionReq) ProtoMessage() {}

func (x *RenameSessionReq) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_ligolo_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenameSessionReq.ProtoReflect.Descriptor instead.
func (*RenameSessionReq) Descriptor() ([]byte, []int) {
	return file_protobuf_ligolo_proto_rawDescGZIP(), []int{15}
}

func (x *RenameSessionReq) GetSessionID() string {
	if x != nil {
		return x.SessionID
	}
	return ""
}

func (x *RenameSessionReq) GetAlias() string {
	if x != nil {
		return x.Alias
	}
	return ""
}

type StartRelayReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionID     string                 `protobuf:"bytes,1,opt,name=SessionID,proto3" json:"SessionID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartRelayReq) Reset() {
	*x = StartRelayReq{}
	mi := &file_protobuf_ligolo_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartRelayReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartRelayReq) ProtoMessage() {}

func (x *StartRelayReq) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_ligolo_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartRelayReq.ProtoReflect.Descriptor instead.
func (*StartRelayReq) Descriptor() ([]byte, []int) {
	return file_protobuf_ligolo_proto_rawDescGZIP(), []int{16}
}

func (x *StartRelayReq) GetSessionID() string {
	if x != nil {
		return x.SessionID
	}
	return ""
}

type StopRelayReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionID     string                 `protobuf:"bytes,1,opt,name=SessionID,proto3" json:"SessionID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopRelayReq) Reset() {
	*x = StopRelayReq{}
	mi := &file_protobuf_ligolo_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopRelayReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopRelayReq) ProtoMessage() {}

func (x *StopRelayReq) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_ligolo_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopRelayReq.ProtoReflect.Descriptor instead.
func (*StopRelayReq) Descriptor() ([]byte, []int) {
	return file_protobuf_ligolo_proto_rawDescGZIP(), []int{17}
}

func (x *StopRelayReq) GetSessionID() string {
	if x != nil {
		return x.SessionID
	}
	return ""
}

type KillSessionReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionID     string                 `protobuf:"bytes,1,opt,name=SessionID,proto3" json:"SessionID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KillSessionReq) Reset() {
	*x = KillSessionReq{}
	mi := &file_protobuf_ligolo_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KillSessionReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KillSessionReq) ProtoMessage() {}

func (x *KillSessionReq) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_ligolo_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KillSessionReq.ProtoReflect.Descriptor instead.
func (*KillSessionReq) Descriptor() ([]byte, []int) {
	return file_protobuf_ligolo_proto_rawDescGZIP(), []int{18}
}

func (x *KillSessionReq) GetSessionID() string {
	if x != nil {
		return x.SessionID
	}
	return ""
}

type AddRouteReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionID     string                 `protobuf:"bytes,1,opt,name=SessionID,proto3" json:"SessionID,omitempty"`
	Route         *Route                 `protobuf:"bytes,2,opt,name=Route,proto3" json:"Route,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddRouteReq) Reset() {
	*x = AddRouteReq{}
	mi := &file_protobuf_ligolo_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddRouteReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddRouteReq) ProtoMessage() {}

func (x *AddRouteReq) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_ligolo_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddRouteReq.ProtoReflect.Descriptor instead.
func (*AddRouteReq) Descriptor() ([]byte, []int) {
	return file_protobuf_ligolo_proto_rawDescGZIP(), []int{19}
}

func (x *AddRouteReq) GetSessionID() string {
	if x != nil {
		return x.SessionID
	}
	return ""
}

func (x *AddRouteReq) GetRoute() *Route {
	if x != nil {
		return x.Route
	}
	return nil
}

type EditRouteReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionID     string                 `protobuf:"bytes,1,opt,name=SessionID,proto3" json:"SessionID,omitempty"`
	RouteID       string                 `protobuf:"bytes,2,opt,name=RouteID,proto3" json:"RouteID,omitempty"`
	Route         *Route                 `protobuf:"bytes,3,opt,name=Route,proto3" json:"Route,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EditRouteReq) Reset() {
	*x = EditRouteReq{}
	mi := &file_protobuf_ligolo_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EditRouteReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EditRouteReq) ProtoMessage() {}

func (x *EditRouteReq) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_ligolo_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EditRouteReq.ProtoReflect.Descriptor instead.
func (*EditRouteReq) Descriptor() ([]byte, []int) {
	return file_protobuf_ligolo_proto_rawDescGZIP(), []int{20}
}

func (x *EditRouteReq) GetSessionID() string {
	if x != nil {
		return x.SessionID
	}
	return ""
}

func (x *EditRouteReq) GetRouteID() string {
	if x != nil {
		return x.RouteID
	}
	return ""
}

func (x *EditRouteReq) GetRoute() *Route {
	if x != nil {
		return x.Route
	}
	return nil
}

type MoveRouteReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OldSessionID  string                 `protobuf:"bytes,1,opt,name=OldSessionID,proto3" json:"OldSessionID,omitempty"`
	RouteID       string                 `protobuf:"bytes,2,opt,name=RouteID,proto3" json:"RouteID,omitempty"`
	NewSessionID  string                 `protobuf:"bytes,3,opt,name=NewSessionID,proto3" json:"NewSessionID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MoveRouteReq) Reset() {
	*x = MoveRouteReq{}
	mi := &file_protobuf_ligolo_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MoveRouteReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoveRouteReq) ProtoMessage() {}

func (x *MoveRouteReq) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_ligolo_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoveRouteReq.ProtoReflect.Descriptor instead.
func (*MoveRouteReq) Descriptor() ([]byte, []int) {
	return file_protobuf_ligolo_proto_rawDescGZIP(), []int{21}
}

func (x *MoveRouteReq) GetOldSessionID() string {
	if x != nil {
		return x.OldSessionID
	}
	return ""
}

func (x *MoveRouteReq) GetRouteID() string {
	if x != nil {
		return x.RouteID
	}
	return ""
}

func (x *MoveRouteReq) GetNewSessionID() string {
	if x != nil {
		return x.NewSessionID
	}
	return ""
}

type DelRouteReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionID     string                 `protobuf:"bytes,1,opt,name=SessionID,proto3" json:"SessionID,omitempty"`
	RouteID       string                 `protobuf:"bytes,2,opt,name=RouteID,proto3" json:"RouteID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DelRouteReq) Reset() {
	*x = DelRouteReq{}
	mi := &file_protobuf_ligolo_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DelRouteReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelRouteReq) ProtoMessage() {}

func (x *DelRouteReq) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_ligolo_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelRouteReq.ProtoReflect.Descriptor instead.
func (*DelRouteReq) Descriptor() ([]byte, []int) {
	return file_protobuf_ligolo_proto_rawDescGZIP(), []int{22}
}

func (x *DelRouteReq) GetSessionID() string {
	if x != nil {
		return x.SessionID
	}
	return ""
}

func (x *DelRouteReq) GetRouteID() string {
	if x != nil {
		return x.RouteID
	}
	return ""
}

type GenerateAgentReq struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Servers        string                 `protobuf:"bytes,1,opt,name=Servers,proto3" json:"Servers,omitempty"`
	GOOS           string                 `protobuf:"bytes,2,opt,name=GOOS,proto3" json:"GOOS,omitempty"`
	GOARCH         string                 `protobuf:"bytes,3,opt,name=GOARCH,proto3" json:"GOARCH,omitempty"`
	Obfuscate      bool                   `protobuf:"varint,4,opt,name=Obfuscate,proto3" json:"Obfuscate,omitempty"`
	ProxyServer    string                 `protobuf:"bytes,5,opt,name=ProxyServer,proto3" json:"ProxyServer,omitempty"`
	IgnoreEnvProxy bool                   `protobuf:"varint,6,opt,name=IgnoreEnvProxy,proto3" json:"IgnoreEnvProxy,omitempty"`
	// Custom certificate fields for identity-based routing
	CertOrganization string `protobuf:"bytes,7,opt,name=CertOrganization,proto3" json:"CertOrganization,omitempty"` // e.g., "group01"
	CertCommonName   string `protobuf:"bytes,8,opt,name=CertCommonName,proto3" json:"CertCommonName,omitempty"`     // e.g., "group01-workstation-a1b2c3d4"
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GenerateAgentReq) Reset() {
	*x = GenerateAgentReq{}
	mi := &file_protobuf_ligolo_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateAgentReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateAgentReq) ProtoMessage() {}

func (x *GenerateAgentReq) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_ligolo_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateAgentReq.ProtoReflect.Descriptor instead.
func (*GenerateAgentReq) Descriptor() ([]byte, []int) {
	return file_protobuf_ligolo_proto_rawDescGZIP(), []int{23}
}

func (x *GenerateAgentReq) GetServers() string {
	if x != nil {
		return x.Servers
	}
	return ""
}

func (x *GenerateAgentReq) GetGOOS() string {
	if x != nil {
		return x.GOOS
	}
	return ""
}

func (x *GenerateAgentReq) GetGOARCH() string {
	if x != nil {
		return x.GOARCH
	}
	return ""
}

func (x *GenerateAgentReq) GetObfuscate() bool {
	if x != nil {
		return x.Obfuscate
	}
	return false
}

func (x *GenerateAgentReq) GetProxyServer() string {
	if x != nil {
		return x.ProxyServer
	}
	return ""
}

func (x *GenerateAgentReq) GetIgnoreEnvProxy() bool {
	if x != nil {
		return x.IgnoreEnvProxy
	}
	return false
}

func (x *GenerateAgentReq) GetCertOrganization() string {
	if x != nil {
		return x.CertOrganization
	}
	return ""
}

func (x *GenerateAgentReq) GetCertCommonName() string {
	if x != nil {
		return x.CertCommonName
	}
	return ""
}

type GenerateAgentResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentBinary   []byte                 `protobuf:"bytes,1,opt,name=AgentBinary,proto3" json:"AgentBinary,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateAgentResp) Reset() {
	*x = GenerateAgentResp{}
	mi := &file_protobuf_ligolo_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateAgentResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateAgentResp) ProtoMessage() {}

func (x *GenerateAgentResp) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_ligolo_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateAgentResp.ProtoReflect.Descriptor instead.
func (*GenerateAgentResp) Descriptor() ([]byte, []int) {
	return file_protobuf_ligolo_proto_rawDescGZIP(), []int{24}
}

func (x *GenerateAgentResp) GetAgentBinary() []byte {
	if x != nil {
		return x.AgentBinary
	}
	return nil
}

type TracerouteReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IP            string                 `protobuf:"bytes,1,opt,name=IP,proto3" json:"IP,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TracerouteReq) Reset() {
	*x = TracerouteReq{}
	mi := &file_protobuf_ligolo_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TracerouteReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TracerouteReq) ProtoMessage() {}

func (x *TracerouteReq) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_ligolo_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TracerouteReq.ProtoReflect.Descriptor instead.
func (*TracerouteReq) Descriptor() ([]byte, []int) {
	return file_protobuf_ligolo_proto_rawDescGZIP(), []int{25}
}

func (x *TracerouteReq) GetIP() string {
	if x != nil {
		return x.IP
	}
	return ""
}

type TracerouteResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Trace         []*Traceroute          `protobuf:"bytes,1,rep,name=Trace,proto3" json:"Trace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TracerouteResp) Reset() {
	*x = TracerouteResp{}
	mi := &file_protobuf_ligolo_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TracerouteResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TracerouteResp) ProtoMessage() {}

func (x *TracerouteResp) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_ligolo_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TracerouteResp.ProtoReflect.Descriptor instead.
func (*TracerouteResp) Descriptor() ([]byte, []int) {
	return file_protobuf_ligolo_proto_rawDescGZIP(), []int{26}
}

func (x *TracerouteResp) GetTrace() []*Traceroute {
	if x != nil {
		return x.Trace
	}
	return nil
}

type GetCertsResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Certs         []*Cert                `protobuf:"bytes,1,rep,name=Certs,proto3" json:"Certs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCertsResp) Reset() {
	*x = GetCertsResp{}
	mi := &file_protobuf_ligolo_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCertsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCertsResp) ProtoMessage() {}

func (x *GetCertsResp) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_ligolo_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCertsResp.ProtoReflect.Descriptor instead.
func (*GetCertsResp) Descriptor() ([]byte, []int) {
	return file_protobuf_ligolo_proto_rawDescGZIP(), []int{27}
}

func (x *GetCertsResp) GetCerts() []*Cert {
	if x != nil {
		return x.Certs
	}
	return nil
}

type RegenCertReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegenCertReq) Reset() {
	*x = RegenCertReq{}
	mi := &file_protobuf_ligolo_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegenCertReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegenCertReq) ProtoMessage() {}

func (x *RegenCertReq) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_ligolo_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegenCertReq.ProtoReflect.Descriptor instead.
func (*RegenCertReq) Descriptor() ([]byte, []int) {
	return file_protobuf_ligolo_proto_rawDescGZIP(), []int{28}
}

func (x *RegenCertReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetOperatorsResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Operators     []*Operator            `protobuf:"bytes,1,rep,name=Operators,proto3" json:"Operators,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOperatorsResp) Reset() {
	*x = GetOperatorsResp{}
	mi := &file_protobuf_ligolo_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOperatorsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOperatorsResp) ProtoMessage() {}

func (x *GetOperatorsResp) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_ligolo_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOperatorsResp.ProtoReflect.Descriptor instead.
func (*GetOperatorsResp) Descriptor() ([]byte, []int) {
	return file_protobuf_ligolo_proto_rawDescGZIP(), []int{29}
}

func (x *GetOperatorsResp) GetOperators() []*Operator {
	if x != nil {
		return x.Operators
	}
	return nil
}

type ExportOperatorReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExportOperatorReq) Reset() {
	*x = ExportOperatorReq{}
	mi := &file_protobuf_ligolo_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExportOperatorReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportOperatorReq) ProtoMessage() {}

func (x *ExportOperatorReq) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_ligolo_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportOperatorReq.ProtoReflect.Descriptor instead.
func (*ExportOperatorReq) Descriptor() ([]byte, []int) {
	return file_protobuf_ligolo_proto_rawDescGZIP(), []int{30}
}

func (x *ExportOperatorReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ExportOperatorResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Operator      *Operator              `protobuf:"bytes,1,opt,name=Operator,proto3" json:"Operator,omitempty"`
	Config        []byte                 `protobuf:"bytes,2,opt,name=Config,proto3" json:"Config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExportOperatorResp) Reset() {
	*x = ExportOperatorResp{}
	mi := &file_protobuf_ligolo_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExportOperatorResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportOperatorResp) ProtoMessage() {}

func (x *ExportOperatorResp) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_ligolo_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportOperatorResp.ProtoReflect.Descriptor instead.
func (*ExportOperatorResp) Descriptor() ([]byte, []int) {
	return file_protobuf_ligolo_proto_rawDescGZIP(), []int{31}
}

func (x *ExportOperatorResp) GetOperator() *Operator {
	if x != nil {
		return x.Operator
	}
	return nil
}

func (x *ExportOperatorResp) GetConfig() []byte {
	if x != nil {
		return x.Config
	}
	return nil
}

type AddOperatorReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Operator      *Operator              `protobuf:"bytes,1,opt,name=Operator,proto3" json:"Operator,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddOperatorReq) Reset() {
	*x = AddOperatorReq{}
	mi := &file_protobuf_ligolo_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddOperatorReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddOperatorReq) ProtoMessage() {}

func (x *AddOperatorReq) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_ligolo_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddOperatorReq.ProtoReflect.Descriptor instead.
func (*AddOperatorReq) Descriptor() ([]byte, []int) {
	return file_protobuf_ligolo_proto_rawDescGZIP(), []int{32}
}

func (x *AddOperatorReq) GetOperator() *Operator {
	if x != nil {
		return x.Operator
	}
	return nil
}

type AddOperatorResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Operator      *Operator              `protobuf:"bytes,1,opt,name=Operator,proto3" json:"Operator,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddOperatorResp) Reset() {
	*x = AddOperatorResp{}
	mi := &file_protobuf_ligolo_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddOperatorResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddOperatorResp) ProtoMessage() {}

func (x *AddOperatorResp) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_ligolo_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddOperatorResp.ProtoReflect.Descriptor instead.
func (*AddOperatorResp) Descriptor() ([]byte, []int) {
	return file_protobuf_ligolo_proto_rawDescGZIP(), []int{33}
}

func (x *AddOperatorResp) GetOperator() *Operator {
	if x != nil {
		return x.Operator
	}
	return nil
}

type DelOperatorReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DelOperatorReq) Reset() {
	*x = DelOperatorReq{}
	mi := &file_protobuf_ligolo_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DelOperatorReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelOperatorReq) ProtoMessage() {}

func (x *DelOperatorReq) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_ligolo_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelOperatorReq.ProtoReflect.Descriptor instead.
func (*DelOperatorReq) Descriptor() ([]byte, []int) {
	return file_protobuf_ligolo_proto_rawDescGZIP(), []int{34}
}

func (x *DelOperatorReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type PromoteOperatorReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PromoteOperatorReq) Reset() {
	*x = PromoteOperatorReq{}
	mi := &file_protobuf_ligolo_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PromoteOperatorReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PromoteOperatorReq) ProtoMessage() {}

func (x *PromoteOperatorReq) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_ligolo_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PromoteOperatorReq.ProtoReflect.Descriptor instead.
func (*PromoteOperatorReq) Descriptor() ([]byte, []int) {
	return file_protobuf_ligolo_proto_rawDescGZIP(), []int{35}
}

func (x *PromoteOperatorReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type DemoteOperatorReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DemoteOperatorReq) Reset() {
	*x = DemoteOperatorReq{}
	mi := &file_protobuf_ligolo_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DemoteOperatorReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DemoteOperatorReq) ProtoMessage() {}

func (x *DemoteOperatorReq) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_ligolo_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DemoteOperatorReq.ProtoReflect.Descriptor instead.
func (*DemoteOperatorReq) Descriptor() ([]byte, []int) {
	return file_protobuf_ligolo_proto_rawDescGZIP(), []int{36}
}

func (x *DemoteOperatorReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetMetadataResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Operator      *Operator              `protobuf:"bytes,1,opt,name=Operator,proto3" json:"Operator,omitempty"`
	Config        *Config                `protobuf:"bytes,2,opt,name=Config,proto3" json:"Config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMetadataResp) Reset() {
	*x = GetMetadataResp{}
	mi := &file_protobuf_ligolo_proto_msgTypes[37]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMetadataResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMetadataResp) ProtoMessage() {}

func (x *GetMetadataResp) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_ligolo_proto_msgTypes[37]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMetadataResp.ProtoReflect.Descriptor instead.
func (*GetMetadataResp) Descriptor() ([]byte, []int) {
	return file_protobuf_ligolo_proto_rawDescGZIP(), []int{37}
}

func (x *GetMetadataResp) GetOperator() *Operator {
	if x != nil {
		return x.Operator
	}
	return nil
}

func (x *GetMetadataResp) GetConfig() *Config {
	if x != nil {
		return x.Config
	}
	return nil
}

// Network probe request/response
type ProbeNetworkReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionID     string                 `protobuf:"bytes,1,opt,name=SessionID,proto3" json:"SessionID,omitempty"`       // Agent session ID to execute probe
	Targets       []string               `protobuf:"bytes,2,rep,name=Targets,proto3" json:"Targets,omitempty"`           // IPs to probe (batch)
	Method        string                 `protobuf:"bytes,3,opt,name=Method,proto3" json:"Method,omitempty"`             // "icmp", "tcp", "udp", "auto"
	TCPPorts      []int32                `protobuf:"varint,4,rep,packed,name=TCPPorts,proto3" json:"TCPPorts,omitempty"` // [22, 80, 135, 139, 443, 445, 3389, 8080]
	UDPPort       int32                  `protobuf:"varint,5,opt,name=UDPPort,proto3" json:"UDPPort,omitempty"`          // 53 (DNS)
	TimeoutMs     int32                  `protobuf:"varint,6,opt,name=TimeoutMs,proto3" json:"TimeoutMs,omitempty"`      // Per-target timeout (default: 2000ms)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProbeNetworkReq) Reset() {
	*x = ProbeNetworkReq{}
	mi := &file_protobuf_ligolo_proto_msgTypes[38]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProbeNetworkReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProbeNetworkReq) ProtoMessage() {}

func (x *ProbeNetworkReq) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_ligolo_proto_msgTypes[38]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProbeNetworkReq.ProtoReflect.Descriptor instead.
func (*ProbeNetworkReq) Descriptor() ([]byte, []int) {
	return file_protobuf_ligolo_proto_rawDescGZIP(), []int{38}
}

func (x *ProbeNetworkReq) GetSessionID() string {
	if x != nil {
		return x.SessionID
	}
	return ""
}

func (x *ProbeNetworkReq) GetTargets() []string {
	if x != nil {
		return x.Targets
	}
	return nil
}

func (x *ProbeNetworkReq) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *ProbeNetworkReq) GetTCPPorts() []int32 {
	if x != nil {
		return x.TCPPorts
	}
	return nil
}

func (x *ProbeNetworkReq) GetUDPPort() int32 {
	if x != nil {
		return x.UDPPort
	}
	return 0
}

func (x *ProbeNetworkReq) GetTimeoutMs() int32 {
	if x != nil {
		return x.TimeoutMs
	}
	return 0
}

type ProbeNetworkResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*ProbeResult         `protobuf:"bytes,1,rep,name=Results,proto3" json:"Results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProbeNetworkResp) Reset() {
	*x = ProbeNetworkResp{}
	mi := &file_protobuf_ligolo_proto_msgTypes[39]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProbeNetworkResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProbeNetworkResp) ProtoMessage() {}

func (x *ProbeNetworkResp) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_ligolo_proto_msgTypes[39]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProbeNetworkResp.ProtoReflect.Descriptor instead.
func (*ProbeNetworkResp) Descriptor() ([]byte, []int) {
	return file_protobuf_ligolo_proto_rawDescGZIP(), []int{39}
}

func (x *ProbeNetworkResp) GetResults() []*ProbeResult {
	if x != nil {
		return x.Results
	}
	return nil
}

type ProbeResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Target        string                 `protobuf:"bytes,1,opt,name=Target,proto3" json:"Target,omitempty"`            // IP address tested
	IsReachable   bool                   `protobuf:"varint,2,opt,name=IsReachable,proto3" json:"IsReachable,omitempty"` // True if any probe succeeded
	LatencyMs     int32                  `protobuf:"varint,3,opt,name=LatencyMs,proto3" json:"LatencyMs,omitempty"`     // Round-trip time (0 if unreachable)
	Method        string                 `protobuf:"bytes,4,opt,name=Method,proto3" json:"Method,omitempty"`            // "icmp", "tcp:22", "tcp:443", "udp:53"
	Error         string                 `protobuf:"bytes,5,opt,name=Error,proto3" json:"Error,omitempty"`              // Error message if probe failed
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProbeResult) Reset() {
	*x = ProbeResult{}
	mi := &file_protobuf_ligolo_proto_msgTypes[40]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProbeResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProbeResult) ProtoMessage() {}

func (x *ProbeResult) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_ligolo_proto_msgTypes[40]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProbeResult.ProtoReflect.Descriptor instead.
func (*ProbeResult) Descriptor() ([]byte, []int) {
	return file_protobuf_ligolo_proto_rawDescGZIP(), []int{40}
}

func (x *ProbeResult) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *ProbeResult) GetIsReachable() bool {
	if x != nil {
		return x.IsReachable
	}
	return false
}

func (x *ProbeResult) GetLatencyMs() int32 {
	if x != nil {
		return x.LatencyMs
	}
	return 0
}

func (x *ProbeResult) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *ProbeResult) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_protobuf_ligolo_proto protoreflect.FileDescriptor

const file_protobuf_ligolo_proto_rawDesc = "" +
	"\n" +
	"\x15protobuf/ligolo.proto\x12\x06ligolo\x1a\x1fgoogle/protobuf/timestamp.proto\"\a\n" +
	"\x05Empty\"7\n" +
	"\x05Error\x12\x16\n" +
	"\x06Object\x18\x01 \x01(\fR\x06Object\x12\x16\n" +
	"\x06Reason\x18\x02 \x01(\tR\x06Reason\"/\n" +
	"\x05Event\x12\x12\n" +
	"\x04Type\x18\x01 \x01(\x05R\x04Type\x12\x12\n" +
	"\x04Data\x18\x02 \x01(\tR\x04Data\"\xdb\x03\n" +
	"\aSession\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\tR\x02ID\x12\x14\n" +
	"\x05Alias\x18\x02 \x01(\tR\x05Alias\x12\x1a\n" +
	"\bHostname\x18\x03 \x01(\tR\bHostname\x12\x1d\n" +
	"\x03Tun\x18\x04 \x01(\v2\v.ligolo.TunR\x03Tun\x12 \n" +
	"\vIsConnected\x18\x05 \x01(\bR\vIsConnected\x12\x1e\n" +
	"\n" +
	"IsRelaying\x18\x06 \x01(\bR\n" +
	"IsRelaying\x121\n" +
	"\n" +
	"Interfaces\x18\a \x03(\v2\x11.ligolo.InterfaceR\n" +
	"Interfaces\x124\n" +
	"\vRedirectors\x18\b \x03(\v2\x12.ligolo.RedirectorR\vRedirectors\x128\n" +
	"\tFirstSeen\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tFirstSeen\x126\n" +
	"\bLastSeen\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\bLastSeen\x12*\n" +
	"\x10CertOrganization\x18\v \x01(\tR\x10CertOrganization\x12&\n" +
	"\x0eCertCommonName\x18\f \x01(\tR\x0eCertCommonName\"@\n" +
	"\x03Tun\x12\x12\n" +
	"\x04Name\x18\x01 \x01(\tR\x04Name\x12%\n" +
	"\x06Routes\x18\x02 \x03(\v2\r.ligolo.RouteR\x06Routes\"1\n" +
	"\tInterface\x12\x12\n" +
	"\x04Name\x18\x01 \x01(\tR\x04Name\x12\x10\n" +
	"\x03IPs\x18\x02 \x03(\tR\x03IPs\"c\n" +
	"\x05Route\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\tR\x02ID\x12\x12\n" +
	"\x04Cidr\x18\x02 \x01(\tR\x04Cidr\x12\x1e\n" +
	"\n" +
	"IsLoopback\x18\x03 \x01(\bR\n" +
	"IsLoopback\x12\x16\n" +
	"\x06Metric\x18\x04 \x01(\x05R\x06Metric\"\\\n" +
	"\n" +
	"Redirector\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\tR\x02ID\x12\x1a\n" +
	"\bProtocol\x18\x02 \x01(\tR\bProtocol\x12\x12\n" +
	"\x04From\x18\x03 \x01(\tR\x04From\x12\x0e\n" +
	"\x02To\x18\x04 \x01(\tR\x02To\"n\n" +
	"\x04Cert\x12\x12\n" +
	"\x04Name\x18\x01 \x01(\tR\x04Name\x12\x1e\n" +
	"\n" +
	"ExpiryDate\x18\x02 \x01(\tR\n" +
	"ExpiryDate\x12 \n" +
	"\vCertificate\x18\x03 \x01(\fR\vCertificate\x12\x10\n" +
	"\x03Key\x18\x04 \x01(\fR\x03Key\"\x9e\x01\n" +
	"\bOperator\x12\x12\n" +
	"\x04Name\x18\x01 \x01(\tR\x04Name\x12\x18\n" +
	"\aIsAdmin\x18\x02 \x01(\bR\aIsAdmin\x12\x16\n" +
	"\x06Server\x18\x03 \x01(\tR\x06Server\x12\x1a\n" +
	"\bIsOnline\x18\x04 \x01(\bR\bIsOnline\x12 \n" +
	"\x04Cert\x18\x05 \x01(\v2\f.ligolo.CertR\x04Cert\x12\x0e\n" +
	"\x02CA\x18\x06 \x01(\fR\x02CA\"R\n" +
	"\x06Config\x12&\n" +
	"\x0eOperatorServer\x18\x01 \x01(\tR\x0eOperatorServer\x12 \n" +
	"\vAgentServer\x18\x02 \x01(\tR\vAgentServer\"\x86\x01\n" +
	"\n" +
	"Traceroute\x12\x1e\n" +
	"\n" +
	"IsInternal\x18\x01 \x01(\bR\n" +
	"IsInternal\x12\x18\n" +
	"\aSession\x18\x02 \x01(\tR\aSession\x12\x14\n" +
	"\x05Iface\x18\x03 \x01(\tR\x05Iface\x12\x10\n" +
	"\x03Via\x18\x04 \x01(\tR\x03Via\x12\x16\n" +
	"\x06Metric\x18\x05 \x01(\x05R\x06Metric\"p\n" +
	"\x10AddRedirectorReq\x12\x1c\n" +
	"\tSessionID\x18\x01 \x01(\tR\tSessionID\x12\x1a\n" +
	"\bProtocol\x18\x02 \x01(\tR\bProtocol\x12\x12\n" +
	"\x04From\x18\x03 \x01(\tR\x04From\x12\x0e\n" +
	"\x02To\x18\x04 \x01(\tR\x02To\"T\n" +
	"\x10DelRedirectorReq\x12\x1c\n" +
	"\tSessionID\x18\x01 \x01(\tR\tSessionID\x12\"\n" +
	"\fRedirectorID\x18\x02 \x01(\tR\fRedirectorID\">\n" +
	"\x0fGetSessionsResp\x12+\n" +
	"\bSessions\x18\x01 \x03(\v2\x0f.ligolo.SessionR\bSessions\"F\n" +
	"\x10RenameSessionReq\x12\x1c\n" +
	"\tSessionID\x18\x01 \x01(\tR\tSessionID\x12\x14\n" +
	"\x05Alias\x18\x02 \x01(\tR\x05Alias\"-\n" +
	"\rStartRelayReq\x12\x1c\n" +
	"\tSessionID\x18\x01 \x01(\tR\tSessionID\",\n" +
	"\fStopRelayReq\x12\x1c\n" +
	"\tSessionID\x18\x01 \x01(\tR\tSessionID\".\n" +
	"\x0eKillSessionReq\x12\x1c\n" +
	"\tSessionID\x18\x01 \x01(\tR\tSessionID\"P\n" +
	"\vAddRouteReq\x12\x1c\n" +
	"\tSessionID\x18\x01 \x01(\tR\tSessionID\x12#\n" +
	"\x05Route\x18\x02 \x01(\v2\r.ligolo.RouteR\x05Route\"k\n" +
	"\fEditRouteReq\x12\x1c\n" +
	"\tSessionID\x18\x01 \x01(\tR\tSessionID\x12\x18\n" +
	"\aRouteID\x18\x02 \x01(\tR\aRouteID\x12#\n" +
	"\x05Route\x18\x03 \x01(\v2\r.ligolo.RouteR\x05Route\"p\n" +
	"\fMoveRouteReq\x12\"\n" +
	"\fOldSessionID\x18\x01 \x01(\tR\fOldSessionID\x12\x18\n" +
	"\aRouteID\x18\x02 \x01(\tR\aRouteID\x12\"\n" +
	"\fNewSessionID\x18\x03 \x01(\tR\fNewSessionID\"E\n" +
	"\vDelRouteReq\x12\x1c\n" +
	"\tSessionID\x18\x01 \x01(\tR\tSessionID\x12\x18\n" +
	"\aRouteID\x18\x02 \x01(\tR\aRouteID\"\x94\x02\n" +
	"\x10GenerateAgentReq\x12\x18\n" +
	"\aServers\x18\x01 \x01(\tR\aServers\x12\x12\n" +
	"\x04GOOS\x18\x02 \x01(\tR\x04GOOS\x12\x16\n" +
	"\x06GOARCH\x18\x03 \x01(\tR\x06GOARCH\x12\x1c\n" +
	"\tObfuscate\x18\x04 \x01(\bR\tObfuscate\x12 \n" +
	"\vProxyServer\x18\x05 \x01(\tR\vProxyServer\x12&\n" +
	"\x0eIgnoreEnvProxy\x18\x06 \x01(\bR\x0eIgnoreEnvProxy\x12*\n" +
	"\x10CertOrganization\x18\a \x01(\tR\x10CertOrganization\x12&\n" +
	"\x0eCertCommonName\x18\b \x01(\tR\x0eCertCommonName\"5\n" +
	"\x11GenerateAgentResp\x12 \n" +
	"\vAgentBinary\x18\x01 \x01(\fR\vAgentBinary\"\x1f\n" +
	"\rTracerouteReq\x12\x0e\n" +
	"\x02IP\x18\x01 \x01(\tR\x02IP\":\n" +
	"\x0eTracerouteResp\x12(\n" +
	"\x05Trace\x18\x01 \x03(\v2\x12.ligolo.TracerouteR\x05Trace\"2\n" +
	"\fGetCertsResp\x12\"\n" +
	"\x05Certs\x18\x01 \x03(\v2\f.ligolo.CertR\x05Certs\"\"\n" +
	"\fRegenCertReq\x12\x12\n" +
	"\x04Name\x18\x01 \x01(\tR\x04Name\"B\n" +
	"\x10GetOperatorsResp\x12.\n" +
	"\tOperators\x18\x01 \x03(\v2\x10.ligolo.OperatorR\tOperators\"'\n" +
	"\x11ExportOperatorReq\x12\x12\n" +
	"\x04Name\x18\x01 \x01(\tR\x04Name\"Z\n" +
	"\x12ExportOperatorResp\x12,\n" +
	"\bOperator\x18\x01 \x01(\v2\x10.ligolo.OperatorR\bOperator\x12\x16\n" +
	"\x06Config\x18\x02 \x01(\fR\x06Config\">\n" +
	"\x0eAddOperatorReq\x12,\n" +
	"\bOperator\x18\x01 \x01(\v2\x10.ligolo.OperatorR\bOperator\"?\n" +
	"\x0fAddOperatorResp\x12,\n" +
	"\bOperator\x18\x01 \x01(\v2\x10.ligolo.OperatorR\bOperator\"$\n" +
	"\x0eDelOperatorReq\x12\x12\n" +
	"\x04Name\x18\x01 \x01(\tR\x04Name\"(\n" +
	"\x12PromoteOperatorReq\x12\x12\n" +
	"\x04Name\x18\x01 \x01(\tR\x04Name\"'\n" +
	"\x11DemoteOperatorReq\x12\x12\n" +
	"\x04Name\x18\x01 \x01(\tR\x04Name\"g\n" +
	"\x0fGetMetadataResp\x12,\n" +
	"\bOperator\x18\x01 \x01(\v2\x10.ligolo.OperatorR\bOperator\x12&\n" +
	"\x06Config\x18\x02 \x01(\v2\x0e.ligolo.ConfigR\x06Config\"\xb5\x01\n" +
	"\x0fProbeNetworkReq\x12\x1c\n" +
	"\tSessionID\x18\x01 \x01(\tR\tSessionID\x12\x18\n" +
	"\aTargets\x18\x02 \x03(\tR\aTargets\x12\x16\n" +
	"\x06Method\x18\x03 \x01(\tR\x06Method\x12\x1a\n" +
	"\bTCPPorts\x18\x04 \x03(\x05R\bTCPPorts\x12\x18\n" +
	"\aUDPPort\x18\x05 \x01(\x05R\aUDPPort\x12\x1c\n" +
	"\tTimeoutMs\x18\x06 \x01(\x05R\tTimeoutMs\"A\n" +
	"\x10ProbeNetworkResp\x12-\n" +
	"\aResults\x18\x01 \x03(\v2\x13.ligolo.ProbeResultR\aResults\"\x93\x01\n" +
	"\vProbeResult\x12\x16\n" +
	"\x06Target\x18\x01 \x01(\tR\x06Target\x12 \n" +
	"\vIsReachable\x18\x02 \x01(\bR\vIsReachable\x12\x1c\n" +
	"\tLatencyMs\x18\x03 \x01(\x05R\tLatencyMs\x12\x16\n" +
	"\x06Method\x18\x04 \x01(\tR\x06Method\x12\x14\n" +
	"\x05Error\x18\x05 \x01(\tR\x05Error2\xf7\n" +
	"\n" +
	"\x06Ligolo\x12(\n" +
	"\x04Join\x12\r.ligolo.Empty\x1a\r.ligolo.Event\"\x000\x01\x127\n" +
	"\vGetMetadata\x12\r.ligolo.Empty\x1a\x17.ligolo.GetMetadataResp\"\x00\x127\n" +
	"\vGetSessions\x12\r.ligolo.Empty\x1a\x17.ligolo.GetSessionsResp\"\x00\x12:\n" +
	"\rRenameSession\x12\x18.ligolo.RenameSessionReq\x1a\r.ligolo.Empty\"\x00\x126\n" +
	"\vKillSession\x12\x16.ligolo.KillSessionReq\x1a\r.ligolo.Empty\"\x00\x124\n" +
	"\n" +
	"StartRelay\x12\x15.ligolo.StartRelayReq\x1a\r.ligolo.Empty\"\x00\x122\n" +
	"\tStopRelay\x12\x14.ligolo.StopRelayReq\x1a\r.ligolo.Empty\"\x00\x120\n" +
	"\bAddRoute\x12\x13.ligolo.AddRouteReq\x1a\r.ligolo.Empty\"\x00\x122\n" +
	"\tEditRoute\x12\x14.ligolo.EditRouteReq\x1a\r.ligolo.Empty\"\x00\x122\n" +
	"\tMoveRoute\x12\x14.ligolo.MoveRouteReq\x1a\r.ligolo.Empty\"\x00\x120\n" +
	"\bDelRoute\x12\x13.ligolo.DelRouteReq\x1a\r.ligolo.Empty\"\x00\x12:\n" +
	"\rAddRedirector\x12\x18.ligolo.AddRedirectorReq\x1a\r.ligolo.Empty\"\x00\x12:\n" +
	"\rDelRedirector\x12\x18.ligolo.DelRedirectorReq\x1a\r.ligolo.Empty\"\x00\x121\n" +
	"\bGetCerts\x12\r.ligolo.Empty\x1a\x14.ligolo.GetCertsResp\"\x00\x122\n" +
	"\tRegenCert\x12\x14.ligolo.RegenCertReq\x1a\r.ligolo.Empty\"\x00\x129\n" +
	"\fGetOperators\x12\r.ligolo.Empty\x1a\x18.ligolo.GetOperatorsResp\"\x00\x12I\n" +
	"\x0eExportOperator\x12\x19.ligolo.ExportOperatorReq\x1a\x1a.ligolo.ExportOperatorResp\"\x00\x12@\n" +
	"\vAddOperator\x12\x16.ligolo.AddOperatorReq\x1a\x17.ligolo.AddOperatorResp\"\x00\x126\n" +
	"\vDelOperator\x12\x16.ligolo.DelOperatorReq\x1a\r.ligolo.Empty\"\x00\x12>\n" +
	"\x0fPromoteOperator\x12\x1a.ligolo.PromoteOperatorReq\x1a\r.ligolo.Empty\"\x00\x12<\n" +
	"\x0eDemoteOperator\x12\x19.ligolo.DemoteOperatorReq\x1a\r.ligolo.Empty\"\x00\x12F\n" +
	"\rGenerateAgent\x12\x18.ligolo.GenerateAgentReq\x1a\x19.ligolo.GenerateAgentResp\"\x00\x12=\n" +
	"\n" +
	"Traceroute\x12\x15.ligolo.TracerouteReq\x1a\x16.ligolo.TracerouteResp\"\x00\x12C\n" +
	"\fProbeNetwork\x12\x17.ligolo.ProbeNetworkReq\x1a\x18.ligolo.ProbeNetworkResp\"\x00B,Z*github.com/ttpreport/ligolo-mp/v2/protobufb\x06proto3"

var (
	file_protobuf_ligolo_proto_rawDescOnce sync.Once
	file_protobuf_ligolo_proto_rawDescData []byte
)

func file_protobuf_ligolo_proto_rawDescGZIP() []byte {
	file_protobuf_ligolo_proto_rawDescOnce.Do(func() {
		file_protobuf_ligolo_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protobuf_ligolo_proto_rawDesc), len(file_protobuf_ligolo_proto_rawDesc)))
	})
	return file_protobuf_ligolo_proto_rawDescData
}

var file_protobuf_ligolo_proto_msgTypes = make([]protoimpl.MessageInfo, 41)
var file_protobuf_ligolo_proto_goTypes = []any{
	(*Empty)(nil),                 // 0: ligolo.Empty
	(*Error)(nil),                 // 1: ligolo.Error
	(*Event)(nil),                 // 2: ligolo.Event
	(*Session)(nil),               // 3: ligolo.Session
	(*Tun)(nil),                   // 4: ligolo.Tun
	(*Interface)(nil),             // 5: ligolo.Interface
	(*Route)(nil),                 // 6: ligolo.Route
	(*Redirector)(nil),            // 7: ligolo.Redirector
	(*Cert)(nil),                  // 8: ligolo.Cert
	(*Operator)(nil),              // 9: ligolo.Operator
	(*Config)(nil),                // 10: ligolo.Config
	(*Traceroute)(nil),            // 11: ligolo.Traceroute
	(*AddRedirectorReq)(nil),      // 12: ligolo.AddRedirectorReq
	(*DelRedirectorReq)(nil),      // 13: ligolo.DelRedirectorReq
	(*GetSessionsResp)(nil),       // 14: ligolo.GetSessionsResp
	(*RenameSessionReq)(nil),      // 15: ligolo.RenameSessionReq
	(*StartRelayReq)(nil),         // 16: ligolo.StartRelayReq
	(*StopRelayReq)(nil),          // 17: ligolo.StopRelayReq
	(*KillSessionReq)(nil),        // 18: ligolo.KillSessionReq
	(*AddRouteReq)(nil),           // 19: ligolo.AddRouteReq
	(*EditRouteReq)(nil),          // 20: ligolo.EditRouteReq
	(*MoveRouteReq)(nil),          // 21: ligolo.MoveRouteReq
	(*DelRouteReq)(nil),           // 22: ligolo.DelRouteReq
	(*GenerateAgentReq)(nil),      // 23: ligolo.GenerateAgentReq
	(*GenerateAgentResp)(nil),     // 24: ligolo.GenerateAgentResp
	(*TracerouteReq)(nil),         // 25: ligolo.TracerouteReq
	(*TracerouteResp)(nil),        // 26: ligolo.TracerouteResp
	(*GetCertsResp)(nil),          // 27: ligolo.GetCertsResp
	(*RegenCertReq)(nil),          // 28: ligolo.RegenCertReq
	(*GetOperatorsResp)(nil),      // 29: ligolo.GetOperatorsResp
	(*ExportOperatorReq)(nil),     // 30: ligolo.ExportOperatorReq
	(*ExportOperatorResp)(nil),    // 31: ligolo.ExportOperatorResp
	(*AddOperatorReq)(nil),        // 32: ligolo.AddOperatorReq
	(*AddOperatorResp)(nil),       // 33: ligolo.AddOperatorResp
	(*DelOperatorReq)(nil),        // 34: ligolo.DelOperatorReq
	(*PromoteOperatorReq)(nil),    // 35: ligolo.PromoteOperatorReq
	(*DemoteOperatorReq)(nil),     // 36: ligolo.DemoteOperatorReq
	(*GetMetadataResp)(nil),       // 37: ligolo.GetMetadataResp
	(*ProbeNetworkReq)(nil),       // 38: ligolo.ProbeNetworkReq
	(*ProbeNetworkResp)(nil),      // 39: ligolo.ProbeNetworkResp
	(*ProbeResult)(nil),           // 40: ligolo.ProbeResult
	(*timestamppb.Timestamp)(nil), // 41: google.protobuf.Timestamp
}
var file_protobuf_ligolo_proto_depIdxs = []int32{
	4,  // 0: ligolo.Session.Tun:type_name -> ligolo.Tun
	5,  // 1: ligolo.Session.Interfaces:type_name -> ligolo.Interface
	7,  // 2: ligolo.Session.Redirectors:type_name -> ligolo.Redirector
	41, // 3: ligolo.Session.FirstSeen:type_name -> google.protobuf.Timestamp
	41, // 4: ligolo.Session.LastSeen:type_name -> google.protobuf.Timestamp
	6,  // 5: ligolo.Tun.Routes:type_name -> ligolo.Route
	8,  // 6: ligolo.Operator.Cert:type_name -> ligolo.Cert
	3,  // 7: ligolo.GetSessionsResp.Sessions:type_name -> ligolo.Session
	6,  // 8: ligolo.AddRouteReq.Route:type_name -> ligolo.Route
	6,  // 9: ligolo.EditRouteReq.Route:type_name -> ligolo.Route
	11, // 10: ligolo.TracerouteResp.Trace:type_name -> ligolo.Traceroute
	8,  // 11: ligolo.GetCertsResp.Certs:type_name -> ligolo.Cert
	9,  // 12: ligolo.GetOperatorsResp.Operators:type_name -> ligolo.Operator
	9,  // 13: ligolo.ExportOperatorResp.Operator:type_name -> ligolo.Operator
	9,  // 14: ligolo.AddOperatorReq.Operator:type_name -> ligolo.Operator
	9,  // 15: ligolo.AddOperatorResp.Operator:type_name -> ligolo.Operator
	9,  // 16: ligolo.GetMetadataResp.Operator:type_name -> ligolo.Operator
	10, // 17: ligolo.GetMetadataResp.Config:type_name -> ligolo.Config
	40, // 18: ligolo.ProbeNetworkResp.Results:type_name -> ligolo.ProbeResult
	0,  // 19: ligolo.Ligolo.Join:input_type -> ligolo.Empty
	0,  // 20: ligolo.Ligolo.GetMetadata:input_type -> ligolo.Empty
	0,  // 21: ligolo.Ligolo.GetSessions:input_type -> ligolo.Empty
	15, // 22: ligolo.Ligolo.RenameSession:input_type -> ligolo.RenameSessionReq
	18, // 23: ligolo.Ligolo.KillSession:input_type -> ligolo.KillSessionReq
	16, // 24: ligolo.Ligolo.StartRelay:input_type -> ligolo.StartRelayReq
	17, // 25: ligolo.Ligolo.StopRelay:input_type -> ligolo.StopRelayReq
	19, // 26: ligolo.Ligolo.AddRoute:input_type -> ligolo.AddRouteReq
	20, // 27: ligolo.Ligolo.EditRoute:input_type -> ligolo.EditRouteReq
	21, // 28: ligolo.Ligolo.MoveRoute:input_type -> ligolo.MoveRouteReq
	22, // 29: ligolo.Ligolo.DelRoute:input_type -> ligolo.DelRouteReq
	12, // 30: ligolo.Ligolo.AddRedirector:input_type -> ligolo.AddRedirectorReq
	13, // 31: ligolo.Ligolo.DelRedirector:input_type -> ligolo.DelRedirectorReq
	0,  // 32: ligolo.Ligolo.GetCerts:input_type -> ligolo.Empty
	28, // 33: ligolo.Ligolo.RegenCert:input_type -> ligolo.RegenCertReq
	0,  // 34: ligolo.Ligolo.GetOperators:input_type -> ligolo.Empty
	30, // 35: ligolo.Ligolo.ExportOperator:input_type -> ligolo.ExportOperatorReq
	32, // 36: ligolo.Ligolo.AddOperator:input_type -> ligolo.AddOperatorReq
	34, // 37: ligolo.Ligolo.DelOperator:input_type -> ligolo.DelOperatorReq
	35, // 38: ligolo.Ligolo.PromoteOperator:input_type -> ligolo.PromoteOperatorReq
	36, // 39: ligolo.Ligolo.DemoteOperator:input_type -> ligolo.DemoteOperatorReq
	23, // 40: ligolo.Ligolo.GenerateAgent:input_type -> ligolo.GenerateAgentReq
	25, // 41: ligolo.Ligolo.Traceroute:input_type -> ligolo.TracerouteReq
	38, // 42: ligolo.Ligolo.ProbeNetwork:input_type -> ligolo.ProbeNetworkReq
	2,  // 43: ligolo.Ligolo.Join:output_type -> ligolo.Event
	37, // 44: ligolo.Ligolo.GetMetadata:output_type -> ligolo.GetMetadataResp
	14, // 45: ligolo.Ligolo.GetSessions:output_type -> ligolo.GetSessionsResp
	0,  // 46: ligolo.Ligolo.RenameSession:output_type -> ligolo.Empty
	0,  // 47: ligolo.Ligolo.KillSession:output_type -> ligolo.Empty
	0,  // 48: ligolo.Ligolo.StartRelay:output_type -> ligolo.Empty
	0,  // 49: ligolo.Ligolo.StopRelay:output_type -> ligolo.Empty
	0,  // 50: ligolo.Ligolo.AddRoute:output_type -> ligolo.Empty
	0,  // 51: ligolo.Ligolo.EditRoute:output_type -> ligolo.Empty
	0,  // 52: ligolo.Ligolo.MoveRoute:output_type -> ligolo.Empty
	0,  // 53: ligolo.Ligolo.DelRoute:output_type -> ligolo.Empty
	0,  // 54: ligolo.Ligolo.AddRedirector:output_type -> ligolo.Empty
	0,  // 55: ligolo.Ligolo.DelRedirector:output_type -> ligolo.Empty
	27, // 56: ligolo.Ligolo.GetCerts:output_type -> ligolo.GetCertsResp
	0,  // 57: ligolo.Ligolo.RegenCert:output_type -> ligolo.Empty
	29, // 58: ligolo.Ligolo.GetOperators:output_type -> ligolo.GetOperatorsResp
	31, // 59: ligolo.Ligolo.ExportOperator:output_type -> ligolo.ExportOperatorResp
	33, // 60: ligolo.Ligolo.AddOperator:output_type -> ligolo.AddOperatorResp
	0,  // 61: ligolo.Ligolo.DelOperator:output_type -> ligolo.Empty
	0,  // 62: ligolo.Ligolo.PromoteOperator:output_type -> ligolo.Empty
	0,  // 63: ligolo.Ligolo.DemoteOperator:output_type -> ligolo.Empty
	24, // 64: ligolo.Ligolo.GenerateAgent:output_type -> ligolo.GenerateAgentResp
	26, // 65: ligolo.Ligolo.Traceroute:output_type -> ligolo.TracerouteResp
	39, // 66: ligolo.Ligolo.ProbeNetwork:output_type -> ligolo.ProbeNetworkResp
	43, // [43:67] is the sub-list for method output_type
	19, // [19:43] is the sub-list for method input_type
	19, // [19:19] is the sub-list for extension type_name
	19, // [19:19] is the sub-list for extension extendee
	0,  // [0:19] is the sub-list for field type_name
}

func init() { file_protobuf_ligolo_proto_init() }
func file_protobuf_ligolo_proto_init() {
	if File_protobuf_ligolo_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protobuf_ligolo_proto_rawDesc), len(file_protobuf_ligolo_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   41,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protobuf_ligolo_proto_goTypes,
		DependencyIndexes: file_protobuf_ligolo_proto_depIdxs,
		MessageInfos:      file_protobuf_ligolo_proto_msgTypes,
	}.Build()
	File_protobuf_ligolo_proto = out.File
	file_protobuf_ligolo_proto_goTypes = nil
	file_protobuf_ligolo_proto_depIdxs = nil
}
